/*
 * datagym-design build
 * --------------------------------------------------------------------------
 * Reads the JSON token manifest in `tokens/` and emits, into `dist/`:
 *   primitives.css  - raw brand scales as :root custom properties
 *   tokens.css      - datagym form: plain :root (light) + [data-theme='dark']
 *   theme.css       - quest form: Tailwind v4 @theme {} + [data-theme='light']
 *   fonts.css       - self-hosted @font-face (woff2 vendored into dist/fonts/)
 *   tokens.js/.d.ts - resolved hex literals for JS consumers (ReactFlow/DagPanel)
 *
 * One source of truth, two CSS dialects. Zero runtime dependencies.
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS = join(ROOT, 'tokens');
const DIST = join(ROOT, 'dist');
const FONTS_OUT = join(DIST, 'fonts');

const readJSON = (f) => JSON.parse(readFileSync(join(TOKENS, f), 'utf8'));
const primitives = readJSON('primitives.json');
const datagym = readJSON('semantic.datagym.json');
const quest = readJSON('semantic.quest.json');
const dag = readJSON('dag.json');

// ── primitive lookup ──────────────────────────────────────────────────────────
const primMap = new Map(); // 'group.key' -> hex
for (const [group, entries] of Object.entries(primitives)) {
  if (group.startsWith('_')) continue;
  for (const [key, val] of Object.entries(entries)) primMap.set(`${group}.${key}`, val);
}

const REF = /^\$([a-zA-Z]+)\.([a-zA-Z0-9-]+)$/;

/**
 * Resolve a manifest value. `$group.key` -> a primitive; anything else
 * (hex, rgba(), var(), color-mix(), gradients, font stacks) passes through.
 * mode 'var'     -> primitive refs become var(--group-key)   (datagym; imports primitives.css)
 * mode 'literal' -> primitive refs become the resolved hex   (quests; self-contained)
 */
function resolve(value, mode) {
  if (typeof value !== 'string') return value;
  const m = value.match(REF);
  if (!m) return value;
  const path = `${m[1]}.${m[2]}`;
  if (!primMap.has(path)) throw new Error(`Unknown primitive ref: ${value}`);
  return mode === 'var' ? `var(--${m[1]}-${m[2]})` : primMap.get(path);
}

const header = (what) =>
  `/*\n * ${what}\n * GENERATED by scripts/build.mjs from tokens/*.json - do not edit by hand.\n */\n`;

// ── primitives.css ────────────────────────────────────────────────────────────
function emitPrimitivesCss() {
  let body = '';
  for (const [group, entries] of Object.entries(primitives)) {
    if (group.startsWith('_')) continue;
    body += `\n  /* ${group} */\n`;
    for (const [key, val] of Object.entries(entries)) body += `  --${group}-${key}: ${val};\n`;
  }
  return `${header('datagym-design raw brand scales - theme-independent.')}:root {${body}}\n`;
}

// ── tokens.css (datagym) ──────────────────────────────────────────────────────
function emitTokensCss() {
  const light = [];
  const dark = [];
  for (const [name, def] of Object.entries(datagym)) {
    if (name.startsWith('_')) continue;
    if (def.light === undefined) throw new Error(`datagym token ${name} has no 'light' value`);
    light.push(`  ${name}: ${resolve(def.light, 'var')};`);
    if (def.dark !== undefined) dark.push(`  ${name}: ${resolve(def.dark, 'var')};`);
  }
  return (
    header('datagym design tokens - plain :root + [data-theme=\'dark\'] custom properties.') +
    `@import './primitives.css';\n@import './fonts.css';\n\n` +
    `:root {\n${light.join('\n')}\n}\n\n` +
    `[data-theme='dark'] {\n${dark.join('\n')}\n}\n`
  );
}

// ── theme.css (quests) ────────────────────────────────────────────────────────
const LAB_ACCENT_DOC =
  `/*\n` +
  ` * Per-lab accent contract\n` +
  ` * ----------------------------------------------------------------------------\n` +
  ` * --lab-accent         bright accent (dark mode + every fill/edge/focus ring)\n` +
  ` * --lab-accent-strong  darker accent for accent-as-text on light surfaces\n` +
  ` * Both default to dbt's coral, so dbt-quest needs no override. A new quest\n` +
  ` * re-flavours every accent surface by setting these once on :root.\n` +
  ` */\n`;

function emitThemeCss() {
  const theme = [];
  const light = [];
  for (const [name, def] of Object.entries(quest)) {
    if (name.startsWith('_')) continue;
    if (def.dark === undefined) throw new Error(`quest token ${name} has no 'dark' value`);
    theme.push(`  ${name}: ${resolve(def.dark, 'literal')};`);
    if (def.light !== undefined) light.push(`  ${name}: ${resolve(def.light, 'literal')};`);
  }
  return (
    header('datagym-design quest theme - Tailwind v4 @theme {} (dark default) + light override.') +
    `@import './fonts.css';\n\n` +
    LAB_ACCENT_DOC +
    `@theme {\n${theme.join('\n')}\n}\n\n` +
    `[data-theme='light'] {\n${light.join('\n')}\n}\n`
  );
}

// ── tokens.js / tokens.d.ts (JS consumers) ────────────────────────────────────
function resolveDeep(node) {
  if (typeof node === 'string') return resolve(node, 'literal');
  const out = {};
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith('_')) continue;
    out[k] = resolveDeep(v);
  }
  return out;
}

function emitTokensJs() {
  const resolved = resolveDeep(dag);
  return (
    header('datagym-design DAG colours - resolved hex literals for ReactFlow/DagPanel.') +
    `export const dag = ${JSON.stringify(resolved, null, 2)};\n`
  );
}

const TOKENS_DTS =
  header('Type declarations for dist/tokens.js') +
  `type ThemePair = { dark: string; light: string };\n` +
  `type LayerColors = { source: string; staging: string; intermediate: string; mart: string };\n\n` +
  `export declare const dag: {\n` +
  `  layer: { dark: LayerColors; light: LayerColors };\n` +
  `  fail: ThemePair;\n` +
  `  idleDot: ThemePair;\n` +
  `  edge: ThemePair;\n` +
  `  bgDot: ThemePair;\n` +
  `  controlsBg: ThemePair;\n` +
  `  controlsBorder: ThemePair;\n` +
  `};\n`;

// ── fonts ─────────────────────────────────────────────────────────────────────
// [ source in node_modules, vendored filename, css family, style, weight range ]
const FONTS = [
  ['@fontsource-variable/inter/files/inter-latin-wght-normal.woff2', 'inter-latin-wght-normal.woff2', 'Inter', 'normal', '100 900'],
  ['@fontsource-variable/inter/files/inter-latin-wght-italic.woff2', 'inter-latin-wght-italic.woff2', 'Inter', 'italic', '100 900'],
  ['@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2', 'jetbrains-mono-latin-wght-normal.woff2', 'JetBrains Mono', 'normal', '100 800'],
  ['@fontsource/poppins/files/poppins-latin-500-normal.woff2', 'poppins-latin-500-normal.woff2', 'Poppins', 'normal', '500'],
  ['@fontsource/poppins/files/poppins-latin-600-normal.woff2', 'poppins-latin-600-normal.woff2', 'Poppins', 'normal', '600'],
  ['@fontsource/poppins/files/poppins-latin-700-normal.woff2', 'poppins-latin-700-normal.woff2', 'Poppins', 'normal', '700'],
];

// Latin subset (Basic Latin + Latin-1 Supplement) - covers EN/PT/ES/FR/DE/IT.
const UNICODE_LATIN =
  'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,' +
  'U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD';

function emitFonts() {
  let css = header('datagym-design self-hosted web fonts - latin subset, woff2.');
  for (const [src, file, family, style, weight] of FONTS) {
    const abs = join(ROOT, 'node_modules', src);
    if (!existsSync(abs)) {
      throw new Error(`Missing font source: ${src}\nRun \`npm install\` in datagym-design first.`);
    }
    copyFileSync(abs, join(FONTS_OUT, file));
    css +=
      `@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: ${style};\n` +
      `  font-display: swap;\n` +
      `  font-weight: ${weight};\n` +
      `  src: url('./fonts/${file}') format('woff2');\n` +
      `  unicode-range: ${UNICODE_LATIN};\n` +
      `}\n`;
  }
  return css;
}

// ── primitives.js / primitives.d.ts (JS consumers needing raw hex values) ─────
function emitPrimitivesJs() {
  const clean = {};
  for (const [group, entries] of Object.entries(primitives)) {
    if (group.startsWith('_')) continue;
    clean[group] = entries;
  }
  return (
    header('datagym-design raw brand primitives - resolved hex literals for JS consumers.') +
    `export const primitives = ${JSON.stringify(clean, null, 2)};\n`
  );
}

function emitPrimitivesDts() {
  const groups = Object.keys(primitives).filter(k => !k.startsWith('_'));
  const props = groups.map(g => `  ${g}: Record<string, string>;`).join('\n');
  return (
    header('Type declarations for dist/primitives.js') +
    `export declare const primitives: {\n${props}\n};\n`
  );
}

// ── write ─────────────────────────────────────────────────────────────────────
rmSync(DIST, { recursive: true, force: true });
mkdirSync(FONTS_OUT, { recursive: true });

const fontsCss = emitFonts(); // copies woff2 first, then returns css
writeFileSync(join(DIST, 'primitives.css'), emitPrimitivesCss());
writeFileSync(join(DIST, 'primitives.js'), emitPrimitivesJs());
writeFileSync(join(DIST, 'primitives.d.ts'), emitPrimitivesDts());
writeFileSync(join(DIST, 'tokens.css'), emitTokensCss());
writeFileSync(join(DIST, 'theme.css'), emitThemeCss());
writeFileSync(join(DIST, 'fonts.css'), fontsCss);
writeFileSync(join(DIST, 'tokens.js'), emitTokensJs());
writeFileSync(join(DIST, 'tokens.d.ts'), TOKENS_DTS);

console.log('datagym-design: built dist/ (primitives.css/.js/.d.ts, tokens.css, theme.css, fonts.css, tokens.js, tokens.d.ts + 6 fonts)');
